# type C-b ? to see keybindings

# bind -n KEY COMMAND — no prefix required for the binding to trigger.
# bind -r KEY COMMAND — “repeat” while holding the key down.
# bind -T TABLE KEY COMMAND — bind only within a specific key table (e.g., copy-mode).
# bind -f FILE — load bindings from a file.
# bind -a KEY COMMAND — use key “alternates” (additional key variants).
# bind -w KEY_COMMAND (if applicable in your tmux version) — treat as a “window” key binding (varies by version/features)
# Can be combined, e.g. `bind -T copy-mode -n -r Up send-keys -X scroll-up`

# Simpler reload of tmux config file
bind r source-file ~/.tmux.conf \; display-message "Reloaded!"

# ---- Basics ----

set -g mouse on
set -g history-limit 100000
set -g set-clipboard on
setw -g monitor-activity on
set -g visual-activity on
set -g bell-action any

# Reduce delay when pressing Escape in Vim
set -sg escape-time 10

set -gq allow-passthrough on

# Terminal Colors
set -g default-terminal "tmux-256color"
set -ga terminal-overrides ",*256col*:Tc"

# ---- Session/Client ----
bind S choose-session
bind N new-session
bind C switch-client -l
bind D detach-client
bind R refresh-client \; display-message "Client Reloaded!"
bind K list-keys
bind H list-commands
bind : command-prompt

# ---- Windows ----

bind c new-window
bind Q confirm-before -p "kill-window #W? (y/n)" kill-window
bind p previous-window
bind n next-window
bind w choose-window
bind o last-window

# Start numbering windows from 1 instead of 0
set -g base-index 1
# and renumber them on window creation/deletion.
set -g renumber-windows on

# ---- Panes ----

bind | split-window -h
bind - split-window -v
set -g pane-border-style "fg=#3b4261"
set -g pane-active-border-style "fg=#7aa2f7"

bind q confirm-before -p "kill-pane #P? (y/n)" kill-pane
bind P display-panes
set -g display-panes-time 2000

bind s select-pane -t :.+
bind h select-pane -L
bind j select-pane -D
bind k select-pane -U
bind l select-pane -R

# bind -r: repeatable
bind -r C-Left resize-pane -L 5
bind -r C-Down resize-pane -D 5
bind -r C-Up resize-pane -U 5
bind -r C-Right resize-pane -R 5
bind z resize-pane -Z

# ---- Modes ----

# Copy mode
bind [ copy-mode
bind ] paste-buffer

# Enable vi keys in copy mode
set-window-option -g mode-keys vi

bind v send-keys -X begin-selection
bind y send-keys -X copy-selection-and-cancel
bind Y send-keys -X copy-line
bind V send-keys -X rectangle-toggle
bind / command-prompt -i -p "search up:" "send-keys -X search-backward '%%'"
bind ? command-prompt -i -p "search down:" "send-keys -X search-forward '%%'"
bind f send-keys -X search-again
bind g send-keys -X top-line
bind G send-keys -X bottom-line
bind b choose-buffer

bind-key -T copy-mode-vi Escape send-keys -X cancel

# ---- Plugins ----

# tmux plugin manager
set -g @plugin "tmux-plugins/tpm"

# Catppuccin colorscheme
set -g @plugin "catppuccin/tmux"
set -g @catppuccin_flavor "mocha"
# Gruvbox colorscheme
# set -g @plugin "egel/tmux-gruvbox"

# Sensible defaults https://github.com/tmux-plugins/tmux-sensible
set -g @plugin "tmux-plugins/tmux-sensible"

# Save and restore tmux sessions across system restarts, preserving panes and windows
# prefix + Ctrl-s - save
# prefix + Ctrl-r - restore
set -g @plugin "tmux-plugins/tmux-resurrect"

# Continuous saving of tmux environment with automatic restore on tmux start
set -g @plugin "tmux-plugins/tmux-continuum"
set -g @continuum-restore "on"

# Copy to system clipboard from tmux
set -g @plugin "tmux-plugins/tmux-yank"

# Initialize tmux plugin manager (keep this line at the bottom of .tmux.conf)
run "~/.tmux/plugins/tpm/tpm"
