# Prefix
unbind-key C-b
set -g prefix C-a
bind-key C-a send-prefix

# Simpler reload of tmux config file
bind r source-file ~/.tmux.conf \; display-message "Reloaded!"

# Start numbering windows from 1 instead of 0 and renumber them on window creation/deletion.
set -g base-index 1
set -g renumber-windows on
# tmux plugin manager
set -g @plugin "tmux-plugins/tpm"
# Sensible defaults https://github.com/tmux-plugins/tmux-sensible
set -g @plugin "tmux-plugins/tmux-sensible"
# colorscheme
set -g @plugin "egel/tmux-gruvbox"

# 256-colors
set -g default-terminal "screen-256color"
# tmux-resurrect
set -gq allow-passthrough on
# Restore tmux env after system restart
set -g @plugin "tmux-plugins/tmux-resurrect"
# saves tmux env - auto start tmux when computer/server is on
set -g @plugin "tmux-plugins/tmux-continuum"
set -g @continuum-restore "on"

# splits panes
bind '|' split-window -h
bind '-' split-window -v

# Initialize tmux plugin manager (keep this line at the bottom of .tmux.conf)
run "~/.tmux/plugins/tpm/tpm"
